[WIP] Tests for Uri.php
maintaina-com/Http pull request #8
Opened 2022-01-13 12:34 UTC by daweeb

Many functions have a Throw exception listed in phpdocu, but no test to trigger it.
Is this Wanted? @midahp
https://github.com/daweeb/Http/blob/06ff3334b051c556e2bd297cc7ee63efb20b0d0e/src/Uri.php#L363

Done
-  Host
-  Port

ToDo:
- fix Fragment Test
- remove comments
-  csfixer/phpformat
-  authority 
-  scheme
-  user info
- nullStandartPort

2022-01-18 09:48 UTC, midahp requested changes
Please solve the mentioned problems and try to add the necessary checks in Uri.php.
Also try to add tests for the `with*` methods to make sure they don't modify the original object

2022-01-18 09:48 UTC, midahp commented on test/UriTest.php
> +    public function testWithInvalidPort()
Add a test for port <0. Then add a check in Uri.php.

2022-01-18 09:48 UTC, midahp commented on test/UriTest.php
> +        $this->assertEquals($uri->getPort(), null);
This is a good example where run into problems with `assertEquals`. This will succeed if `$uri->getPort()` returns 0 (which is what happens here). Use `assertSame` to check the type aswell.
In this case you should use `assertNull($uri->getPort())` though, because you already know you want a `null` to be returned.

2022-01-18 09:48 UTC, midahp commented on test/UriTest.php
> +        $this->assertEquals($uri->getHost(), $host);
If you want to add this check, this test should expect an exception for this value. Then add that exception in Uri.php

2022-01-18 09:48 UTC, midahp commented on test/UriTest.php
> +        $this->assertEquals($uri->getHost(), null);
You should use assertSame('', $uri->getHost());

2022-01-18 09:48 UTC, midahp commented on test/UriTest.php
> +    public function testWithPathRemovesFragmentString()
This test already exists above.

2022-01-18 09:48 UTC, midahp commented on test/UriTest.php
> +        $this->assertEquals($uri->getFragment(), null);
use `assertSame('', $uri->getFragment()`

2022-01-18 09:48 UTC, midahp commented on test/UriTest.php
> +        $this->assertEquals($uri->getScheme(), null);
use `assertSame('', $uri->getScheme())`

2022-01-18 09:48 UTC, midahp commented on test/UriTest.php
> +        $this->assertEquals($uri->getAuthority(), '');
use `assertSame` here

2022-01-18 10:14 UTC, daweeb commented on test/UriTest.php
> +        $this->assertEquals($uri->getAuthority(), '');
done

2022-01-18 10:14 UTC, daweeb commented on test/UriTest.php
> +        $this->assertEquals($uri->getScheme(), null);
done

2022-01-18 10:14 UTC, daweeb commented on test/UriTest.php
> +        $this->assertEquals($uri->getFragment(), null);
done

2022-01-18 10:14 UTC, daweeb commented on test/UriTest.php
> +    public function testWithPathRemovesFragmentString()
removed

2022-01-18 10:19 UTC, daweeb commented on test/UriTest.php
> +        $this->assertEquals($uri->getHost(), null);
done

2022-01-18 10:26 UTC, daweeb commented on test/UriTest.php
> +    public function testWithInvalidPort()
done

2022-01-18 10:38 UTC, daweeb commented on test/UriTest.php
> +        $this->assertEquals($uri->getPort(), null);
done, but hat to add a new if in withport function. There is probably a smarter way of doing this. I will add a link when pushed to repo.

2022-01-18 12:48 UTC, daweeb commented on test/UriTest.php
> +        $this->assertEquals($uri->getHost(), $host);
I added a hostname check, please validate if correct use-case applies here.  Again added a null check.

2022-01-19 07:51 UTC, midahp requested changes
Added some comments.
Also try to add tests for the with* methods to make sure they don't modify the original object

2022-01-19 07:51 UTC, midahp commented on src/Uri.php
> +        if ($host == null) {
Use `if (!$host)` instead

2022-01-19 07:51 UTC, midahp commented on src/Uri.php
> +            throw new InvalidArgumentException('Invalid Hostname, Valid characters for hostnames are ASCII(7) letters.');
This message is not correct right? Not all ASCII letters are valid.

2022-01-19 07:51 UTC, midahp commented on src/Uri.php
> +            throw new InvalidArgumentException('Invalid Portnumber, port must be between 1 and 65535');
Port 0 is valid.

2022-01-19 07:51 UTC, midahp commented on src/Uri.php
> +        if ($port == null) {
use:
```
if (!is_null($port) {
    $port = (int) $port;
}
$ret = clone $this;
$ret->port = $port;
return $ret;
```

2022-01-19 07:51 UTC, midahp commented on test/UriTest.php
> +    public function testWithValidPort()
It would probably be useful to test the edge cases with port = 0 and port = 65535

2022-01-19 07:51 UTC, midahp commented on test/UriTest.php
> +    public function testWithInvalidHost()
Add a test with invalid host that only has ascii characters. Like `test##Host`.
Add tests for valid hosts that use the `-` and the `.` characters.
Add a test for invalid host that starts with the `-` character.

2022-01-19 07:51 UTC, midahp commented on test/UriTest.php
> +    public function testWithNullHost()
I would call this `testWithEmptyHost` but its fine

2022-01-19 09:35 UTC, daweeb commented on test/UriTest.php
> +    public function testWithValidPort()
good idea, done.

2022-01-19 09:37 UTC, daweeb commented on src/Uri.php
> +        if ($host == null) {
done

2022-01-19 09:42 UTC, daweeb commented on src/Uri.php
> +            throw new InvalidArgumentException('Invalid Portnumber, port must be between 1 and 65535');
changed. sry.

2022-01-19 09:46 UTC, daweeb commented on src/Uri.php
> +        if ($port == null) {
done, with error
`1) Horde\Http\Test\UriTest::testWithNullPort Failed asserting that 0 is null`
is this wanted? In the PHPDoc it says 
`  A null value provided for the port is equivalent to removing the port information.`
so i thought it should be null not 0.

2022-01-19 09:48 UTC, daweeb commented on test/UriTest.php
> +    public function testWithNullHost()
changed.

2022-01-19 09:50 UTC, ralflang commented
You are confusing things.

0 is an integer and an invalid port number - you must error.
null is "no port number given" and valid.

Check for null first and skip the port range check if it is null.

2022-01-19 10:16 UTC, daweeb commented on test/UriTest.php
> +    public function testWithInvalidHost()
Added.

2022-01-19 10:23 UTC, daweeb commented on src/Uri.php
> +            throw new InvalidArgumentException('Invalid Hostname, Valid characters for hostnames are ASCII(7) letters.');
changed, sry.

2022-01-19 10:25 UTC, daweeb commented on src/Uri.php
> +        if ($port == null) {
From Ralf:

0 is an integer and an invalid port number - you must error.
null is "no port number given" and valid.

Check for null first and skip the port range check if it is null.

changed it.

2022-01-19 14:10 UTC, midahp commented on src/Uri.php
> +        if ($port >= 65536 || $port <= 0) {
I think you missunderstood. I meant the Exception message needs to  say `between 0 and 65535`. You actually made port 0 invalid in the if. Port 0 is a valid port (as far as I know).

2022-01-19 14:10 UTC, midahp commented on test/UriTest.php
> +    public function testWithValidPortMin()
This needs to be adjusted, because port 0 is a valid port. See other comment about `withPort`

2022-01-19 14:10 UTC, midahp commented on src/Uri.php
> +        if ($port == null) {
Yes I mentioned it in another comment. But my code suggestion should still work. You test just tested the wrong thing.

2022-01-19 14:21 UTC, midahp commented on src/Uri.php
> +        if ($port >= 65536 || $port <= 0) {
My mistake.

2022-01-20 13:33 UTC, merged